name: build and test

on:
  push:
  pull_request:
    branches: [ main, testing_workflow ]
    paths:
      - '**.cs'
      - '**.csproj'


jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore ./RealTimeWeatherMonitoringSystem/Real-time-weather-monitoring-system.sln

      - name: Build
        run: dotnet build ./RealTimeWeatherMonitoringSystem/Real-time-weather-monitoring-system.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./RealTimeWeatherMonitoringSystem/Real-time-weather-monitoring-system.sln --no-restore --verbosity normal